---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag: "glob:our-build-tag-*-deployme"
spec:
  releaseName: prod-app
  chart:
    git: https://github.com/AaronKalair/flux-helm-test.git
    path: charts/helloworld
    ref: master
  values:
    replicaCount: 2
    image: aaronkalair/helm-hello-world:our-build-tag-deployme
    model_version: abc
