---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    # https://docs.fluxcd.io/en/1.17.1/references/helm-operator-integration.html#filters
    filter.fluxcd.io/chart-image: glob:our-build-tag-*-deployme
spec:
  releaseName: prod-app
  chart:
    git: https://github.com/AaronKalair/flux-helm-test.git
    path: charts/helloworld
    ref: master
  values:
    replicaCount: 2
    image: aaronkalair/helm-hello-world:our-build-tag-v9-deployme
    model_version: hij
