apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: hello
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_VERSION
              value: {{ .Values.model_version }}

